# Generated by Django 3.2.8 on 2021-11-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20211115_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
